Titles = {
    "./transcripts/transcript1.txt": "Georgia Voter Suppression",
    "./transcripts/transcript2.txt": "White Supremacy in America Compilation",
    "./transcripts/transcript3.txt": "Waffles + Mochi and Pass the Love",
    "./transcripts/transcript4.txt": "Policing in America Compilation",
    "./transcripts/transcript5.txt": "Conspiracy Theories - Born in America Compilation",
    "./transcripts/transcript6.txt": "If You Don't Know, Now You Know - Government Compilation",
    "./transcripts/transcript7.txt": "ICYMI - Violence Against Women",
    "./transcripts/transcript8.txt": "Celebrating Asian-American Voices & Stories",
    "./transcripts/transcript9.txt": "Trevor Discusses Violence Against Women | Nomzamo Mbatha",
    "./transcripts/transcript10.txt": "Histhery with Desi Lydic - Female Orgasms in Film | Eric Andre",
    "./transcripts/transcript11.txt": "British Royal Family Considers Hiring a Diversity Czar | Michelle Obama",
    "./transcripts/transcript12.txt": "If You Don't Know, Now You Know - America's Power Grid | Kevin Garnett",
    "./transcripts/transcript13.txt": "Racism and Vaccination in the U.S. | Andra Day",
    "./transcripts/transcript14.txt": "GOP Pushes Voter Restrictions | Hugh Evans",
    "./transcripts/transcript15.txt": "Texas Storm Fallout Continues | Sharon McMahon",
    "./transcripts/transcript16.txt": "ICYMI - Heather McGhee on The Sum of Us",
    "./transcripts/transcript17.txt": "This Week's Top Stories - Joe Biden's Scandals & Vaccine Buddy System in Massachusetts",
    "./transcripts/transcript18.txt": "The Magical, Wonderful Road to Impeachment - Day Three | Daniel Kaluuya",
    "./transcripts/transcript19.txt": "The Magical, Wonderful Road to Impeachment - Trump's Lawyers | Radha Blank",
    "./transcripts/transcript20.txt": "India's Farmer Protest | Robin Roberts & Noah Centineo",
    "./transcripts/transcript21.txt": "Joe Biden: The Worst President in History We Can Remember | Atul Gawande & Leonard Fournette",
    "./transcripts/transcript22.txt": "The GameStop Uprising",
    "./transcripts/transcript23.txt": "Coronavirus Updates - Anti-Vaxxers Shut Down Vaccination Site, Rusty Pilots & Childcare Crisis",
    "./transcripts/transcript24.txt": "This Week's Top Stories - Marjorie Taylor Greene Backlash & Alexandria Ocasio-Cortez's Riot Account",
    "./transcripts/transcript25.txt": "Alexandria Ocasio-Cortez Recounts Capitol Riot Attack | Ibram X. Kendi",
    "./transcripts/transcript26.txt": "AOC Recounts Capitol Riot Attack | Ibram X. Kendi",
    "./transcripts/transcript27.txt": "Marjorie Taylor Greene Faces Backlash | Jeremy O. Harris",
    "./transcripts/transcript28.txt": "ICYMI - Amanda Gorman on Making History with The Hill We Climb",
    "./transcripts/transcript29.txt": "Coronavirus Updates - America's Vaccine Rollout Chaos & International Pandemic News",
    "./transcripts/transcript30.txt": "Wall Street Halts GameStop Rally | Regina King & Doug Henwood",
    "./transcripts/transcript31.txt": "Biden Calls for Unity | Amanda Gorman",
    "./transcripts/transcript32.txt": "The GOP Dodges Decision to Impeach Trump | Nnamdi Asomugha",
    "./transcripts/transcript33.txt": "This Week's Top Stories - The FBI Nabs Capitol Rioters, Joe Biden's Inauguration & The NBA Bans Hugs",
    "./transcripts/transcript34.txt": "Biden Clears a Low Bar | Jelani Cobb",
    "./transcripts/transcript35.txt": "Joe Biden's Inauguration | Stacey Abrams",
    "./transcripts/transcript36.txt": "ICYMI - Donald Trump: America's African President",
    "./transcripts/transcript37.txt": "ICYMI - Eli Saslow and Derek Black on Redemption After Renouncing Racism in Rising Out of Hatred",
    "./transcripts/transcript38.txt": "ICYMI - Jonah Goldberg on Suicide of the West and Preserving the American Experiment",
    "./transcripts/transcript39.txt": "Jordan Klepper Fingers the Pulse - Insurrection at the Capitol",
    "./transcripts/transcript40.txt": "ICYMI - Timothy Snyder Discusses On Tyranny and How to Maintain a Democracy",
    "./transcripts/transcript41.txt": "ICYMI - Barack Obama on A Promised Land, Nurturing Future Leaders and Black Lives Matter",
    "./transcripts/transcript42.txt": "ICYMI - How Racist Is Boston?",
    "./transcripts/transcript43.txt": "Jordan Klepper vs. Trump Supporters - The Complete Collection",
    "./transcripts/transcript44.txt": "Republicans Accept Biden's Victory | Barack Obama",
    "./transcripts/transcript45.txt": "Racism in Housing | Brit Bennett & Michael J. Fox",
    "./transcripts/transcript46.txt": "Donald Trump's Fundraising Hustle | Ernest Cline & Rosie Perez",
    "./transcripts/transcript47.txt": "A Look Back at Joe Biden's Journey to the Presidency",
    "./transcripts/transcript48.txt": "ICYMI - Bill Gates on COVID-19 Challenges, Climate Change and Podcasting with Rashida Jones",
    "./transcripts/transcript49.txt": "Back in Black - MAGA Voters Are Fed Up with Fox News | Lucy McBath & Lindsey Vonn",
    "./transcripts/transcript50.txt": "Votegasm 2020: The Awkward Day After | Geraldo Cadava & Evan Osnos",
    "./transcripts/transcript51.txt": "",
    "./transcripts/transcript52.txt": "",
    "./transcripts/transcript53.txt": "",
    "./transcripts/transcript54.txt": "",
    "./transcripts/transcript55.txt": "",
    "./transcripts/transcript56.txt": "",
    "./transcripts/transcript57.txt": "",
    "./transcripts/transcript58.txt": "",
    "./transcripts/transcript59.txt": "",
    "./transcripts/transcript60.txt": "",
    "./transcripts/transcript61.txt": "",
    "./transcripts/transcript62.txt": "",
    "./transcripts/transcript63.txt": "",
    "./transcripts/transcript64.txt": "",
    "./transcripts/transcript65.txt": "",
    "./transcripts/transcript66.txt": "",
    "./transcripts/transcript67.txt": "",
    "./transcripts/transcript68.txt": "",
    "./transcripts/transcript69.txt": "",
    "./transcripts/transcript70.txt": "",
    "./transcripts/transcript71.txt": "",
    "./transcripts/transcript72.txt": "",
    "./transcripts/transcript73.txt": "",
    "./transcripts/transcript74.txt": "",
    "./transcripts/transcript75.txt": ""
}